### ISSUE TITLE
Discord Bot to connect to .env aware MONGODB ports 

### ISSUE THREAD

**Issue by mhmdksh** [givepraise/praise#757]
After the need to run multiple praise instances in our environments for our clients we have to run multiple containers on the same system, and let the a web gateway forward the traffic to each container depending on the specific random port used for the Discord Bot Container.

For example if I changed the Discord Bot port to 27099, it will not work and throw an error while connecting to the mongodb instance

2022-12-27 13:22:39:2239 error: error
2022-12-27 13:22:39:2239 error: Failed to register bot commands
2022-12-27 13:23:05:235 error: Could not connect to database.
/usr/src/packages/discord-bot/node_modules/discord.js/src/client/websocket/WebSocketManager.js:250
        throw new Error(unrecoverableErrorCodeMap[error.code]);
              ^
Error [DisallowedIntents]: Privileged intent provided is not enabled or whitelisted.
    at WebSocketManager.createShards (/usr/src/packages/discord-bot/node_modules/discord.js/src/client/websocket/WebSocketManager.js:250:15)
    at async Client.login (/usr/src/packages/discord-bot/node_modules/discord.js/src/client/Client.js:232:7) {
  code: 'DisallowedIntents'
}

We need the Discord Bot to be aware of the ports used in the .env file as they will be changing with muli-praise setup on same server

**Comment by mhmdksh** [comment]
I reopened the issue, as it is still giving the same error while we run it. 
I think I know where the issue is from though, It's from the .env variable definitions for the multisite we should have something like this: 

![image](https://user-images.githubusercontent.com/52987806/209828821-0cd2da28-68c1-4de2-8d34-2248975f1cf8.png)

Instead of the full http://domainname/ domain for it to work since in this case it should connect with the running services locally on the server and let the proxy gateway do the proxy work for the frontend.

Notice, we need in the environment (While the application is running) the application to think that it's api url is LOCALHOST:$API_PORT That's why it is still not connecting
