### ISSUE TITLE
API to connect to .env aware MONGODB ports 

### ISSUE THREAD

**Issue by mhmdksh** [givepraise/praise#758]
After the need to run multiple praise instances in our environments for our clients we have to run multiple containers on the same system, and let the a web gateway forward the traffic to each container depending on the specific random port used for the API Container.

For example if I changed the API port to 8888, it will not work and throw an error while connecting to the mongodb instance

/usr/src/packages/api/src/database/connection.ts:6
  MONGO_HOST: string;
                                                                ^
Error: Could not connect to database
    at /usr/src/packages/api/src/database/connection.ts:45:11
    at Generator.throw (<anonymous>)
    at rejected (/usr/src/packages/api/src/database/connection.ts:6:65)
/usr/src/packages/api/src/database/connection.ts:6

We need the API to be aware of the ports used in the .env file as they will be changing with muli-praise setup on same server

**Comment by mhmdksh** [comment]
I reopened the issue, as it is still giving the same error while we run it. 
I think I know where the issue is from though, It's from the .env variable definitions for the multisite we should have something like this: 

![image](https://user-images.githubusercontent.com/52987806/209828821-0cd2da28-68c1-4de2-8d34-2248975f1cf8.png)

Instead of the full http://domainname/ domain for it to work since in this case it should connect with the running services locally on the server and let the proxy gateway do the proxy work for the frontend.

Notice, we need in the environment (While the application is running) the application to think that it's api url is LOCALHOST:$API_PORT That's why it is still not connecting
